### ISSUE TITLE
The precision in the paper cannot be achieved

### ISSUE THREAD

**Issue by YoungJT-7274** [jianxiong-zhou/TFE-DCN#1]
I follow your README.md and run your code on THUMOS-14.  But the mAP(0.1:0.5, 0.1:0.7)is 1.3-1.5% lower than in your paper. what is the problem?

**Comment by jianxiong-zhou** [comment]
Modify the '--interval' in options.py from 200 to 10 or 20 and you will get better results.

**Comment by YoungJT-7274** [comment]
Thanks，this modification does improve the mAP by about 0.3%, but there is still a gap of 1% with your paper.

**Comment by jianxiong-zhou** [comment]
Thank you for pointing out the problem. I forgot to change the codes back after ablation studies. Please change Line 102 in model.py to

"out_attention = (out_attention1+out_attention2+out_attention3)/3.0" (multi-layers adjust the attention)

And Line 41 to

"bit_wise_attn = self.channel_conv1(ffeat)" (sharing cov)

And run the codes with --interval 10. I think this time you will get the results.

If you still have problems, please let me know. I will check these uploaded codes this weekend.

**Comment by YoungJT-7274** [comment]
Thank you for your reply. This modification improve the mAP by about 0.25%. Looking forward to your subsequent modification to achieve the precision in the paper.

**Comment by YoungJT-7274** [comment]
Thank you for your reply. This modification improve the mAP by about 0.25% again. There is only a gap of 0.75% with your paper. Looking forward to your subsequent modification to achieve the precision in the paper.

**Comment by jianxiong-zhou** [comment]
Just a small problem. Change 1599 on Line 66 in main.py to 1299. And you will get the results at the 2540-th iteration. Remember to run the codes with --interval 10.

**Comment by YoungJT-7274** [comment]
Sadly, this modification didn't bring any change.
